const title = "Adjectives 😊";
const defaultWords = [
{word:"åben", meaning:"açık"},
{word:"åbenbar", meaning:"apaçık"},
{word:"absolut", meaning:"kesinlikle-mutlak"},
{word:"adskillig", meaning:"çeşitli"},
{word:"ægte", meaning:"gerçek"},
{word:"afgørende", meaning:"hayati-önemli"},
{word:"afhængig", meaning:"bağımlı"},
{word:"aktiv", meaning:"aktif"},
{word:"aktuel", meaning:"güncel"},
{word:"al", meaning:"tüm - bütün"},
{word:"almindelig", meaning:"sıradan - normal"},
{word:"alvorlig", meaning:"ciddi"},
{word:"anderledes", meaning:"farklı"},
{word:"bange", meaning:"korkmuş"},
{word:"bekendt", meaning:"tanıdık"},
{word:"berømt", meaning:"ünlü"},
{word:"bestemt", meaning:"belirli"},
{word:"betydelig", meaning:"önemli"},
{word:"bevidst", meaning:"bilinçli"},
{word:"billig", meaning:"ucuz"},
{word:"beskidt", meaning:"kirli"},
{word:"blød", meaning:"yumuşak"},
{word:"bred", meaning:"geniş"},
{word:"central", meaning:"merkezi"},
{word:"dårlig", meaning:"kötü"},
{word:"dejlig", meaning:"güzel - hoş"},
{word:"dyb", meaning:"derin"},
{word:"dygtig", meaning:"yetenekli"},
{word:"dyr", meaning:"pahalı"},
{word:"effektiv", meaning:"etkili"},
{word:"enkel", meaning:"basit"},
{word:"enorm", meaning:"çok büyük"},
{word:"fælles", meaning:"ortak"},
{word:"færdig", meaning:"hazır"},
{word:"fantastisk", meaning:"harika"},
{word:"farlig", meaning:"tehlikeli"},
{word:"fast", meaning:"sabit"},
{word:"fattig", meaning:"fakir"},
{word:"fin", meaning:"zarif"},
{word:"flot", meaning:"şık"},
{word:"forkert", meaning:"yanlış"},
{word:"forsigtig", meaning:"dikkatli"},
{word:"fri", meaning:"özgür"},
{word:"frisk", meaning:"taze"},
{word:"fuld", meaning:"dolu"},
{word:"gal", meaning:"çılgın"},
{word:"gammel", meaning:"eski"},
{word:"glad", meaning:"mutlu"},
{word:"god", meaning:"iyi"},
{word:"grim", meaning:"çirkin"},
{word:"grov", meaning:"kaba"},
{word:"grundig", meaning:"detaylı"},
{word:"halv", meaning:"yarım"},
{word:"hård", meaning:"sert"},
{word:"hel", meaning:"tam"},
{word:"høj", meaning:"yüksek"},
{word:"hurtig", meaning:"hızlı"},
{word:"interessant", meaning:"ilginç"},
{word:"klar", meaning:"hazır - net"},
{word:"klog", meaning:"akıllı"},
{word:"kold", meaning:"soğuk"},
{word:"kort", meaning:"kısa"},
{word:"kraftig", meaning:"güçlü"},
{word:"lang", meaning:"uzun"},
{word:"langsom", meaning:"yavaş"},
{word:"lav", meaning:"alçak"},
{word:"let", meaning:"kolay"},
{word:"lille", meaning:"küçük"},
{word:"lokal", meaning:"yerel"},
{word:"løs", meaning:"gevşek"},
{word:"lykkelig", meaning:"mutlu"},
{word:"mærkelig", meaning:"garip"},
{word:"moderne", meaning:"modern"},
{word:"mørk", meaning:"karanlık"},
{word:"mulig", meaning:"mümkün"},
{word:"nær", meaning:"yakın"},
{word:"naturlig", meaning:"doğal"},
{word:"nødvendig", meaning:"gerekli"},
{word:"normal", meaning:"normal"},
{word:"ny", meaning:"yeni"},
{word:"offentlig", meaning:"kamu"},
{word:"ond", meaning:"kötü"},
{word:"opmærksom", meaning:"dikkatli"},
{word:"ordentlig", meaning:"düzgün"},
{word:"pæn", meaning:"güzel"},
{word:"parat", meaning:"hazır"},
{word:"personlig", meaning:"kişisel"},
{word:"populær", meaning:"popüler"},
{word:"positiv", meaning:"pozitif"},
{word:"praktisk", meaning:"pratik"},
{word:"privat", meaning:"özel"},
{word:"professionel", meaning:"profesyonel"},
{word:"rar", meaning:"garip"},
{word:"ren", meaning:"temiz"},
{word:"rig", meaning:"zengin"},
{word:"rigtig", meaning:"doğru"},
{word:"rimelig", meaning:"makul"},
{word:"rolig", meaning:"sakin"},
{word:"sand", meaning:"gerçek"},
{word:"sikker", meaning:"güvenli"},
{word:"simpel", meaning:"basit"},
{word:"sjælden", meaning:"nadir"},
{word:"skarp", meaning:"keskin"},
{word:"slem", meaning:"kötü"},
{word:"smuk", meaning:"güzel"},
{word:"sød", meaning:"tatlı"},
{word:"spændende", meaning:"heyecan verici"},
{word:"stærk", meaning:"güçlü"},
{word:"sund", meaning:"sağlıklı"},
{word:"sur", meaning:"sinirli"},
{word:"svag", meaning:"zayıf"},
{word:"svær", meaning:"zor"},
{word:"syg", meaning:"hasta"},
{word:"tidlig", meaning:"erken"},
{word:"tilfreds", meaning:"memnun"},
{word:"tilstrækkelig", meaning:"yeterli"},
{word:"tom", meaning:"boş"},
{word:"tør", meaning:"kuru"},
{word:"træt", meaning:"yorgun"},
{word:"travl", meaning:"meşgul"},
{word:"tung", meaning:"ağır"},
{word:"tyk", meaning:"kalın"},
{word:"tynd", meaning:"ince"},
{word:"typisk", meaning:"tipik"},
{word:"ukendt", meaning:"bilinmeyen"},
{word:"umulig", meaning:"imkansız"},
{word:"ung", meaning:"genç"},
{word:"utrolig", meaning:"inanılmaz"},
{word:"vanskelig", meaning:"zor"},
{word:"varm", meaning:"sıcak"},
{word:"venlig", meaning:"nazik"},
{word:"vild", meaning:"vahşi"},
{word:"voksen", meaning:"yetişkin"},
{word:"vred", meaning:"kızgın"},
{word:"nem", meaning:"kolay"},
{word:"sulten", meaning:"aç"},
{word:"mæt", meaning:"tok"},
{word:"våd", meaning:"ıslak"},
{word:"slank", meaning:"zayıf-fit"},
{word:"uhøflig", meaning:"kaba"},
{word:"sjov", meaning:"eğlenceli"},
{word:"kedelig", meaning:"sıkıcı"},
{word:"rask", meaning:"sağlıklı"},
{word:"høflig", meaning:"kibar (resmi)"},
{word:"smilende", meaning:"güler yüzlü"},
{word:"arbejdsom", meaning:"çalışkan"},
{word:"succesfuld", meaning:"başarılı"},
{word:"imødekommende", meaning:"cana yakın"},
{word:"hjælpsom", meaning:"yardımsever"},
{word:"vidende", meaning:"bilgili"},
{word:"erfaren", meaning:"tecrübeli"},
{word:"interesseret", meaning:"ilgili"},
{word:"lærevillig", meaning:"öğrenmeye açık"},
{word:"ligeglad", meaning:"vurdum duymaz"},
{word:"doven", meaning:"tembel"},
{word:"trist", meaning:"üzgün"},
{word:"glædelig", meaning:"neşeli"},
{word:"nervøs", meaning:"gergin"},
{word:"bekymret", meaning:"endişeli"},
{word:"stresset", meaning:"stresli"},
{word:"afslappet", meaning:"rahat"},
{word:"stolt", meaning:"gururlu"},
{word:"jaloux", meaning:"kıskanç"},
{word:"skuffet", meaning:"hayal kırıklığına uğramış"},
{word:"overrasket", meaning:"şaşırmış"},
{word:"smal", meaning:"dar / ince"},
{word:"bredskuldret", meaning:"geniş omuzlu"},
{word:"overvægtig", meaning:"kilolu"},
{word:"normalvægtig", meaning:"normal kilolu"},
{word:"undervægtig", meaning:"zayıf (sağlık)"},
{word:"skaldet", meaning:"kel"},
{word:"langhåret", meaning:"uzun saçlı"},
{word:"korthåret", meaning:"kısa saçlı"},
{word:"lyshåret", meaning:"sarışın"},
{word:"mørkhåret", meaning:"koyu saçlı"},
{word:"søvnig", meaning:"uykulu"},
{word:"tørstig", meaning:"susamış"},
{word:"ansvarlig", meaning:"sorumlu"},
{word:"pålidelig", meaning:"güvenilir"},
{word:"fleksibel", meaning:"esnek"},
{word:"stabil", meaning:"istikrarlı"},
{word:"teamorienteret", meaning:"takım odaklı"},
{word:"serviceminded", meaning:"müşteri odaklı"},
{word:"engageret", meaning:"hevesli"},
{word:"motiveret", meaning:"motive"},
{word:"struktureret", meaning:"düzenli"},
{word:"organiseret", meaning:"organize"},
{word:"disciplineret", meaning:"disiplinli"},
{word:"stor", meaning:"büyük"},
{word:"lys", meaning:"aydınlık"},
{word:"rummelig", meaning:"ferah"},
{word:"trang", meaning:"sıkışık"},
{word:"stille", meaning:"sessiz"},
{word:"larmende", meaning:"gürültülü"},
{word:"hyggelig", meaning:"huzurlu"},
{word:"komfortabel", meaning:"konforlu"},
{word:"centralt", meaning:"merkezi"},
{word:"tæt på", meaning:"yakın"},
{word:"fjern", meaning:"uzak"},
{word:"skægget", meaning:"sakallı"},
{word:"barberet", meaning:"tıraşlı"},
{word:"krøllet", meaning:"kıvırcık"},
{word:"glat", meaning:"düz (saç)"},
{word:"skøn", meaning:"çok güzel"},
{word:"attraktiv", meaning:"çekici"},
{word:"velklædt", meaning:"iyi giyimli"},
{word:"sjusket", meaning:"bakımsız"}
];