const title = "Verbum-2 🏃‍";
const defaultWords = [
//en çok kullanılan 2'nci 150'lik fiil listesi

{word:"afgøre", meaning:"karar vermek"},
{word:"afholde", meaning:"düzenlemek (etkinlik)"},
{word:"afklare", meaning:"netleştirmek"},
{word:"aflevere", meaning:"teslim etmek"},
{word:"afløse", meaning:"yerine geçmek"},
{word:"afskaffe", meaning:"kaldırmak"},
{word:"afsløre", meaning:"ortaya çıkarmak"},
{word:"afvise", meaning:"reddetmek"},
{word:"analysere", meaning:"analiz etmek"},
{word:"anbefale", meaning:"tavsiye etmek"},
{word:"anerkende", meaning:"tanımak / kabul etmek"},
{word:"angive", meaning:"belirtmek"},
{word:"anmode", meaning:"talep etmek"},
{word:"ansøge", meaning:"başvurmak"},
{word:"antage", meaning:"varsaymak"},
{word:"anvende", meaning:"uygulamak"},
{word:"argumentere", meaning:"argüman sunmak"},
{word:"arrangere", meaning:"organize etmek"},
{word:"beskrive", meaning:"tanımlamak"},
{word:"bestræbe sig", meaning:"çabalamak"},
{word:"bestå", meaning:"geçmek"},
{word:"bidrage", meaning:"katkıda bulunmak"},
{word:"belyse", meaning:"aydınlatmak (konu)"},
{word:"behandle", meaning:"ele almak / tedavi etmek"},
{word:"bekræfte", meaning:"onaylamak"},
{word:"bemærke", meaning:"fark etmek"},
{word:"benytte", meaning:"kullanmak"},
{word:"beskytte", meaning:"korumak"},
{word:"beslutte", meaning:"karar vermek"},
{word:"bestride", meaning:"inkar etmek"},
{word:"bestemme", meaning:"karar vermek"},
{word:"bevise", meaning:"kanıtlamak"},
{word:"betragte", meaning:"değerlendirmek"},
{word:"betone", meaning:"vurgulamak"},
{word:"bevare", meaning:"korumak"},
{word:"bevirke", meaning:"sebep olmak"},
{word:"definere", meaning:"tanımlamak"},
{word:"demonstrere", meaning:"göstermek"},
{word:"diskutere", meaning:"tartışmak"},
{word:"drøfte", meaning:"tartışmak"},
{word:"effektivisere", meaning:"verimli hale getirmek"},
{word:"eksistere", meaning:"var olmak"},
{word:"erkende", meaning:"kabul etmek / fark etmek"},
{word:"erstatte", meaning:"yerine koymak"},
{word:"evaluere", meaning:"değerlendirmek"},
{word:"fastlægge", meaning:"belirlemek"},
{word:"fastslå", meaning:"tespit etmek"},
{word:"fjerne", meaning:"kaldırmak"},
{word:"forandre", meaning:"değiştirmek"},
{word:"forbedre", meaning:"iyileştirmek"},
{word:"forberede", meaning:"hazırlamak"},
{word:"forbinde", meaning:"bağlamak"},
{word:"forbruge", meaning:"tüketmek"},
{word:"fordele", meaning:"dağıtmak"},
{word:"forebygge", meaning:"önlemek"},
{word:"foregå", meaning:"gerçekleşmek"},
{word:"forekomme", meaning:"meydana gelmek"},
{word:"forene", meaning:"birleştirmek"},
{word:"foreslå", meaning:"önermek"},
{word:"forestille sig", meaning:"hayal etmek"},
{word:"foretage", meaning:"gerçekleştirmek"},
{word:"forhandle", meaning:"müzakere etmek"},
{word:"forhindre", meaning:"engellemek"},
{word:"forholde sig", meaning:"ilişki kurmak / yaklaşmak"},
{word:"forklare", meaning:"açıklamak"},
{word:"forlange", meaning:"talep etmek"},
{word:"formidle", meaning:"iletmek"},
{word:"formulere", meaning:"ifade etmek"},
{word:"forøge", meaning:"arttırmak"},
{word:"forsinke", meaning:"geciktirmek"},
{word:"forsvare", meaning:"savunmak"},
{word:"forsvinde", meaning:"yok olmak"},
{word:"fortolke", meaning:"yorumlamak"},
{word:"fortsætte", meaning:"devam etmek"},
{word:"forudsætte", meaning:"varsaymak"},
{word:"forvandle", meaning:"dönüştürmek"},
{word:"forvente", meaning:"beklemek"},
{word:"fremgå", meaning:"ortaya çıkmak"},
{word:"fremhæve", meaning:"vurgulamak"},
{word:"fremlægge", meaning:"sunmak"},
{word:"fremsætte", meaning:"öne sürmek"},
{word:"fremstille", meaning:"üretmek"},
{word:"fremstå", meaning:"görünmek"},
{word:"fungere", meaning:"işlev görmek"},
{word:"garantere", meaning:"garanti etmek"},
{word:"gennemføre", meaning:"gerçekleştirmek"},
{word:"gennemgå", meaning:"gözden geçirmek"},
{word:"gentage", meaning:"tekrar etmek"},
{word:"godkende", meaning:"onaylamak"},
{word:"håndtere", meaning:"yönetmek"},
{word:"identificere", meaning:"tanımlamak"},
{word:"illustrere", meaning:"örneklemek"},
{word:"implementere", meaning:"uygulamak"},
{word:"inddrage", meaning:"dahil etmek"},
{word:"indføre", meaning:"uygulamaya koymak"},
{word:"indgå", meaning:"dahil olmak"},
{word:"indlede", meaning:"başlatmak"},
{word:"indrette", meaning:"düzenlemek"},
{word:"indrømme", meaning:"itiraf etmek"},
{word:"indsamle", meaning:"toplamak"},
{word:"indsætte", meaning:"yerleştirmek"},
{word:"indstille", meaning:"ayarlamak"},
{word:"indtage", meaning:"almak"},
{word:"indtrykke", meaning:"etkilemek"},
{word:"inspirere", meaning:"ilham vermek"},
{word:"installere", meaning:"kurmak"},
{word:"integrere", meaning:"entegre etmek"},
{word:"interessere", meaning:"ilgilenmek"},
{word:"investere", meaning:"yatırım yapmak"},
{word:"invitere", meaning:"davet etmek"},
{word:"justere", meaning:"ayarlamak"},
{word:"klargøre", meaning:"hazırlamak"},
{word:"kombinere", meaning:"birleştirmek"},
{word:"kommunikere", meaning:"iletişim kurmak"},
{word:"koncentrere sig", meaning:"odaklanmak"},
{word:"konkludere", meaning:"sonuç çıkarmak"},
{word:"konstatere", meaning:"tespit etmek"},
{word:"konstruere", meaning:"inşa etmek"},
{word:"kontrollere", meaning:"kontrol etmek"},
{word:"koordinere", meaning:"koordine etmek"},
{word:"kræve", meaning:"gerektirmek"},
{word:"kritiserе", meaning:"eleştirmek"},
{word:"lede", meaning:"yönetmek"},
{word:"lokalisere", meaning:"yerini belirlemek"},
{word:"måle", meaning:"ölçmek"},
{word:"meddele", meaning:"bildirmek"},
{word:"medføre", meaning:"neden olmak"},
{word:"medvirke", meaning:"katkı sağlamak"},
{word:"mindske", meaning:"azaltmak"},
{word:"motivere", meaning:"motive etmek"},
{word:"muliggøre", meaning:"mümkün kılmak"},
{word:"observere", meaning:"gözlemlemek"},
{word:"opbygge", meaning:"oluşturmak"},
{word:"opdage", meaning:"keşfetmek"},
{word:"operere", meaning:"ameliyat etmek"},
{word:"opfatte", meaning:"algılamak"},
{word:"opfinde", meaning:"icat etmek"},
{word:"opfordre", meaning:"teşvik etmek"},
{word:"opføre", meaning:"inşa etmek"},
{word:"opfylde", meaning:"yerine getirmek"},
{word:"opgive", meaning:"vazgeçmek"},
{word:"ophæve", meaning:"iptal etmek"},
{word:"opleve", meaning:"deneyimlemek"},
{word:"oplyse", meaning:"bilgilendirmek"},
{word:"opnå", meaning:"elde etmek"},
{word:"oprette", meaning:"kurmak"},
{word:"opstå", meaning:"ortaya çıkmak"},
{word:"opstille", meaning:"sunmak"},
{word:"optage", meaning:"kaydetmek"},
{word:"optræde", meaning:"sahne almak"},
{word:"overbevise", meaning:"ikna etmek"},
{word:"overføre", meaning:"aktarmak"},
{word:"overholde", meaning:"uymak"},
{word:"overleve", meaning:"hayatta kalmak"},
{word:"overraske", meaning:"şaşırtmak"},
{word:"overtage", meaning:"devralmak"},
{word:"overveje", meaning:"düşünmek"},
{word:"påvirke", meaning:"etkilemek"},
{word:"planlægge", meaning:"planlamak"},
{word:"producere", meaning:"üretmek"},
{word:"reagere", meaning:"tepki vermek"},
{word:"reducere", meaning:"azaltmak"},
{word:"registrere", meaning:"kaydetmek"},
{word:"regulere", meaning:"düzenlemek"},
{word:"repræsentere", meaning:"temsil etmek"},
{word:"respektere", meaning:"saygı göstermek"},
{word:"rette", meaning:"düzeltmek"},
{word:"sammenligne", meaning:"karşılaştırmak"},
{word:"skabe", meaning:"yaratmak"},
{word:"sikre", meaning:"güvence altına almak"},
{word:"specificere", meaning:"belirtmek"},
{word:"strukturere", meaning:"yapılandırmak"},
{word:"studere", meaning:"incelemek"},
{word:"støtte", meaning:"desteklemek"},
{word:"tilføje", meaning:"eklemek"},
{word:"tilpasse", meaning:"uyarlamak"},
{word:"tilsikre", meaning:"garanti etmek"},
{word:"tilskynde", meaning:"teşvik etmek"},
{word:"tilstræbe", meaning:"hedeflemek"},
{word:"undersøge", meaning:"araştırmak"},
{word:"understrege", meaning:"vurgulamak"},
{word:"undgå", meaning:"kaçınmak"},
{word:"udføre", meaning:"gerçekleştirmek"},
{word:"udgøre", meaning:"oluşturmak"},
{word:"udlede", meaning:"sonuç çıkarmak"},
{word:"udnytte", meaning:"faydalanmak"},
{word:"udtrykke", meaning:"ifade etmek"},
{word:"udvide", meaning:"genişletmek"},
{word:"udvikle", meaning:"geliştirmek"},
{word:"vurdere", meaning:"değerlendirmek"},
{word:"være afhængig af", meaning:"bağımlı olmak"},
{word:"ændre sig", meaning:"değişmek"}

];