const title = "Verb Synonyms ♻️ 🏃";
const defaultWords = [
//es anlamlı fiiller listesi

{word:"sige (söylemek)", meaning:"fortælle, udtale"},
{word:"fortælle (anlatmak)", meaning:"sige, forklare"},
{word:"forklare (açıklamak)", meaning:"uddybe, beskrive"},
{word:"snakke (konuşmak)", meaning:"tale"},
{word:"tale (konuşmak)", meaning:"snakke"},
{word:"spørge (sormak)", meaning:"forespørge"},
{word:"svare (cevap vermek)", meaning:"besvare"},
{word:"forstå (anlamak)", meaning:"opfatte"},
{word:"opfatte (algılamak)", meaning:"forstå"},
{word:"tænke (düşünmek)", meaning:"overveje"},
{word:"overveje (düşünmek)", meaning:"tænke, reflektere"},
{word:"mene (düşünmek)", meaning:"synes"},
{word:"synes (düşünmek)", meaning:"mene"},
{word:"se (görmek)", meaning:"observere"},
{word:"observere (gözlemlemek)", meaning:"iagttage"},
{word:"høre (duymak)", meaning:"lytte"},
{word:"lytte (dinlemek)", meaning:"høre"},
{word:"lære (öğrenmek)", meaning:"tilegne sig"},
{word:"studere (incelemek)", meaning:"lære"},
{word:"arbejde (çalışmak)", meaning:"fungere, virke"},
{word:"virke (işlemek)", meaning:"fungere"},
{word:"gøre (yapmak)", meaning:"udføre, lave"},
{word:"lave (yapmak)", meaning:"gøre"},
{word:"begynde (başlamak)", meaning:"starte"},
{word:"starte (başlamak)", meaning:"begynde"},
{word:"slutte (bitirmek)", meaning:"afslutte"},
{word:"afslutte (bitirmek)", meaning:"slutte"},
{word:"fortsætte (devam etmek)", meaning:"blive ved"},
{word:"stoppe (durmak)", meaning:"standse"},
{word:"gå (gitmek)", meaning:"bevæge sig"},
{word:"komme (gelmek)", meaning:"ankomme"},
{word:"rejse (seyahat etmek)", meaning:"tage afsted"},
{word:"flytte (taşınmak)", meaning:"skifte bolig"},
{word:"tage (almak)", meaning:"modtage"},
{word:"modtage (almak)", meaning:"tage imod"},
{word:"give (vermek)", meaning:"overdrage"},
{word:"overdrage (devretmek)", meaning:"give"},
{word:"finde (bulmak)", meaning:"opdage"},
{word:"opdage (keşfetmek)", meaning:"finde"},
{word:"miste (kaybetmek)", meaning:"tabe"},
{word:"tabe (kaybetmek)", meaning:"miste"},
{word:"købe (satın almak)", meaning:"anskaffe"},
{word:"sælge (satmak)", meaning:"afsætte"},
{word:"betale (ödemek)", meaning:"afregne"},
{word:"koste (mal olmak)", meaning:"kræve"},
{word:"åbne (açmak)", meaning:"åbne op"},
{word:"lukke (kapatmak)", meaning:"lukke ned"},
{word:"bruge (kullanmak)", meaning:"anvende"},
{word:"anvende (kullanmak)", meaning:"benytte"},
{word:"benytte (kullanmak)", meaning:"bruge"},
{word:"hjælpe (yardım etmek)", meaning:"assistere"},
{word:"støtte (desteklemek)", meaning:"bakke op"},
{word:"beslutte (karar vermek)", meaning:"afgøre"},
{word:"afgøre (karar vermek)", meaning:"beslutte"},
{word:"vælge (seçmek)", meaning:"udvælge"},
{word:"udvælge (seçmek)", meaning:"vælge"},
{word:"planlægge (planlamak)", meaning:"forberede"},
{word:"forberede (hazırlamak)", meaning:"planlægge"},
{word:"forvente (beklemek)", meaning:"regne med"},
{word:"håbe (umut etmek)", meaning:"ønske"},
{word:"opnå (elde etmek)", meaning:"nå"},
{word:"nå (ulaşmak)", meaning:"opnå"},
{word:"vinde (kazanmak)", meaning:"opnå"},
{word:"lykkes (başarmak)", meaning:"opnå"},
{word:"udvikle (geliştirmek)", meaning:"forbedre"},
{word:"forbedre (iyileştirmek)", meaning:"udvikle"},
{word:"ændre (değiştirmek)", meaning:"forandre"},
{word:"forandre (değiştirmek)", meaning:"ændre"},
{word:"bevare (korumak)", meaning:"holde fast"},
{word:"beskytte (korumak)", meaning:"forsvare"},
{word:"forklare (açıklamak)", meaning:"uddybe"},
{word:"beskrive (tanımlamak)", meaning:"forklare"},
{word:"undersøge (araştırmak)", meaning:"analysere"},
{word:"analysere (analiz etmek)", meaning:"undersøge"},
{word:"vurdere (değerlendirmek)", meaning:"bedømme"},
{word:"bedømme (değerlendirmek)", meaning:"vurdere"},
{word:"sammenligne (karşılaştırmak)", meaning:"holde op imod"},
{word:"konkludere (sonuç çıkarmak)", meaning:"drage konklusion"},
{word:"udtrykke (ifade etmek)", meaning:"formulere"},
{word:"formulere (ifade etmek)", meaning:"udtrykke"},
{word:"påvirke (etkilemek)", meaning:"influerе"},
{word:"influerе (etkilemek)", meaning:"påvirke"}

];