const title = "Verb Antonyms 🎭 🏃";
const defaultWords = [
{word:"åbne (açmak)", meaning:"lukke - lukke ned"},
{word:"lukke (kapatmak)", meaning:"åbne - åbne op"},
{word:"lukke ned (kapatmak)", meaning:"åbne op - åbne"},
{word:"åbne op (açmak)", meaning:"lukke ned - lukke"},
{word:"starte (başlamak)", meaning:"stoppe - slutte"},
{word:"stoppe (durmak)", meaning:"starte - fortsætte"},
{word:"begynde (başlamak)", meaning:"slutte - stoppe"},
{word:"slutte (bitirmek)", meaning:"begynde - starte"},
{word:"fortsætte (devam etmek)", meaning:"stoppe - afslutte"},
{word:"give (vermek)", meaning:"tage - modtage"},
{word:"tage (almak)", meaning:"give"},
{word:"modtage (almak)", meaning:"give"},
{word:"købe (satın almak)", meaning:"sælge"},
{word:"sælge (satmak)", meaning:"købe"},
{word:"finde (bulmak)", meaning:"miste"},
{word:"miste (kaybetmek)", meaning:"finde - opnå"},
{word:"opnå (elde etmek)", meaning:"miste"},
{word:"vinde (kazanmak)", meaning:"tabe"},
{word:"tabe (kaybetmek)", meaning:"vinde"},
{word:"elske (sevmek)", meaning:"hade"},
{word:"hade (nefret etmek)", meaning:"elske"},
{word:"huske (hatırlamak)", meaning:"glemme"},
{word:"glemme (unutmak)", meaning:"huske"},
{word:"komme (gelmek)", meaning:"gå - tage afsted"},
{word:"gå (gitmek)", meaning:"komme"},
{word:"ankomme (varmak)", meaning:"forlade"},
{word:"forlade (ayrılmak)", meaning:"ankomme"},
{word:"stige (yükselmek)", meaning:"falde"},
{word:"falde (düşmek)", meaning:"stige"},
{word:"tænde (açmak)", meaning:"slukke"},
{word:"slukke (kapatmak)", meaning:"tænde"},
{word:"bygge (inşa etmek)", meaning:"rive ned"},
{word:"rive ned (yıkmak)", meaning:"bygge"},
{word:"opbygge (kurmak)", meaning:"nedbryde"},
{word:"nedbryde (yıkmak)", meaning:"opbygge"},
{word:"forbedre (iyileştirmek)", meaning:"forværre"},
{word:"forværre (kötüleştirmek)", meaning:"forbedre"},
{word:"ændre (değiştirmek)", meaning:"bevare"},
{word:"bevare (korumak)", meaning:"ændre"},
{word:"tømme (boşaltmak)", meaning:"fylde"},
{word:"fylde (doldurmak)", meaning:"tømme"},
{word:"binde (bağlamak)", meaning:"løsne"},
{word:"løsne (çözmek)", meaning:"binde"},
{word:"løfte (kaldırmak)", meaning:"sænke"},
{word:"sænke (indirmek)", meaning:"løfte"},
{word:"komme ind (içeri girmek)", meaning:"gå ud"},
{word:"gå ud (dışarı çıkmak)", meaning:"komme ind"},
{word:"sige (söylemek)", meaning:"tie"},
{word:"tale (konuşmak)", meaning:"tie"},
{word:"tie (susmak)", meaning:"sige - tale"},
{word:"arbejde (çalışmak)", meaning:"hvile"},
{word:"hvile (dinlenmek)", meaning:"arbejde"},
{word:"sove (uyumak)", meaning:"vågne"},
{word:"vågne (uyanmak)", meaning:"sove"},
{word:"hjælpe (yardım etmek)", meaning:"skade"},
{word:"skade (zarar vermek)", meaning:"hjælpe"},
{word:"beskytte (korumak)", meaning:"angribe"},
{word:"angribe (saldırmak)", meaning:"beskytte"},
{word:"godkende (onaylamak)", meaning:"afvise - acceptere"},
{word:"acceptere (kabul etmek)", meaning:"afvise - godkende"},
{word:"afvise (reddetmek)", meaning:"godkende - acceptere"},
{word:"indgå (dahil olmak)", meaning:"udelukke"},
{word:"udelukke (hariç tutmak)", meaning:"indgå"},
{word:"inkludere (dahil etmek)", meaning:"ekskludere"},
{word:"ekskludere (hariç tutmak)", meaning:"inkludere"},
{word:"forene (birleştirmek)", meaning:"adskille"},
{word:"adskille (ayırmak)", meaning:"forene"},
{word:"samle (toplamak)", meaning:"sprede"},
{word:"sprede (yaymak)", meaning:"samle"},
{word:"komme tilbage (geri gelmek)", meaning:"gå væk"},
{word:"gå væk (uzaklaşmak)", meaning:"komme tilbage"},
{word:"øge (arttırmak)", meaning:"reducere"},
{word:"reducere (azaltmak)", meaning:"øge"},
{word:"overleve (hayatta kalmak)", meaning:"dø"},
{word:"dø (ölmek)", meaning:"overleve"}
];