const title = "Verbum-1 🧍‍‍";
const defaultWords = [
{word:"ansætte", meaning:"işe almak"},
{word:"arbejde", meaning:"çalışmak"},
{word:"arbejde sammen", meaning:"birlikte çalışmak"},
{word:"bage", meaning:"pişirmek"},
{word:"begynde", meaning:"başlamak"},
{word:"beslutte", meaning:"karar vermek"},
{word:"besøge", meaning:"ziyaret etmek"},
{word:"betale", meaning:"ödemek"},
{word:"blande", meaning:"karıştırmak"},
{word:"blive", meaning:"olmak"},
{word:"bo", meaning:"yaşamak"},
{word:"bringe", meaning:"getirmek"},
{word:"bruge", meaning:"kullanmak"},
{word:"bære", meaning:"taşımak"},
{word:"drikke", meaning:"içmek"},
{word:"fejle", meaning:"başarısız olmak"},
{word:"finde", meaning:"bulmak"},
{word:"flytte", meaning:"taşınmak"},
{word:"forberede", meaning:"hazırlamak"},
{word:"forklare", meaning:"açıklamak"},
{word:"forstå", meaning:"anlamak"},
{word:"fortsætte", meaning:"devam etmek"},
{word:"fortælle", meaning:"anlatmak"},
{word:"forvente", meaning:"beklemek"},
{word:"få", meaning:"almak"},
{word:"fylde", meaning:"doldurmak"},
{word:"fyre", meaning:"işten çıkarmak"},
{word:"give", meaning:"vermek"},
{word:"glemme", meaning:"unutmak"},
{word:"gå", meaning:"gitmek / yürümek"},
{word:"gå ud", meaning:"dışarı çıkmak"},
{word:"gøre", meaning:"yapmak"},
{word:"have", meaning:"sahip olmak"},
{word:"hente", meaning:"getirmek"},
{word:"holde", meaning:"tutmak"},
{word:"huske", meaning:"hatırlamak"},
{word:"høre", meaning:"duymak"},
{word:"hjælpe", meaning:"yardım etmek"},
{word:"håbe", meaning:"umut etmek"},
{word:"koge", meaning:"kaynatmak"},
{word:"komme", meaning:"gelmek"},
{word:"komme ind", meaning:"içeri girmek"},
{word:"komme tilbage", meaning:"geri gelmek"},
{word:"kontakte", meaning:"iletişime geçmek"},
{word:"koste", meaning:"mal olmak"},
{word:"købe", meaning:"satın almak"},
{word:"køre", meaning:"sürmek"},
{word:"kende", meaning:"tanımak"},
{word:"lade", meaning:"izin vermek"},
{word:"lave", meaning:"yapmak"},
{word:"lede", meaning:"aramak"},
{word:"lege", meaning:"oynamak"},
{word:"leve", meaning:"yaşamak"},
{word:"ligge", meaning:"yatmak"},
{word:"lære", meaning:"öğrenmek"},
{word:"læse", meaning:"okumak"},
{word:"løbe", meaning:"koşmak"},
{word:"løfte", meaning:"kaldırmak"},
{word:"lukke", meaning:"kapatmak"},
{word:"lytte", meaning:"dinlemek"},
{word:"mene", meaning:"düşünmek"},
{word:"miste", meaning:"kaybetmek"},
{word:"modtage", meaning:"almak"},
{word:"møde", meaning:"karşılaşmak"},
{word:"mødes", meaning:"buluşmak"},
{word:"opnå", meaning:"elde etmek"},
{word:"overveje", meaning:"düşünmek"},
{word:"planlægge", meaning:"planlamak"},
{word:"prøve", meaning:"denemek"},
{word:"rejse", meaning:"seyahat etmek"},
{word:"sende", meaning:"göndermek"},
{word:"se", meaning:"görmek"},
{word:"sidde", meaning:"oturmak"},
{word:"sige", meaning:"söylemek"},
{word:"skrive", meaning:"yazmak"},
{word:"skære", meaning:"kesmek"},
{word:"slukke", meaning:"kapatmak"},
{word:"slutte", meaning:"bitirmek"},
{word:"snakke", meaning:"konuşmak"},
{word:"sove", meaning:"uyumak"},
{word:"spare", meaning:"biriktirmek"},
{word:"spise", meaning:"yemek"},
{word:"spørge", meaning:"sormak"},
{word:"starte", meaning:"başlamak"},
{word:"stå", meaning:"durmak"},
{word:"stoppe", meaning:"durmak"},
{word:"støtte", meaning:"desteklemek"},
{word:"svare", meaning:"cevap vermek"},
{word:"tage", meaning:"almak"},
{word:"tage med", meaning:"yanına almak"},
{word:"tale", meaning:"konuşmak"},
{word:"tænke", meaning:"düşünmek"},
{word:"tænde", meaning:"açmak"},
{word:"tømme", meaning:"boşaltmak"},
{word:"tro", meaning:"inanmak"},
{word:"tabe", meaning:"kaybetmek"},
{word:"udvikle", meaning:"geliştirmek"},
{word:"være", meaning:"olmak"},
{word:"vælge", meaning:"seçmek"},
{word:"vågne", meaning:"uyanmak"},
{word:"vide", meaning:"bilmek"},
{word:"ville", meaning:"istemek"},
{word:"vinde", meaning:"kazanmak"},
{word:"vurdere", meaning:"değerlendirmek"},
{word:"ønske", meaning:"istemek"},
{word:"åbne", meaning:"açmak"}

];