const title = "Ordsæt-2 💬";

const defaultWords = [

{word:"aktivitet", meaning:"aktivite"},
{word:"ansvar", meaning:"sorumluluk"},
{word:"arbejdsliv", meaning:"iş hayatı"},
{word:"arbejdsplads", meaning:"iş yeri"},
{word:"arbejdsgiver", meaning:"işveren"},
{word:"arbejdstager", meaning:"çalışan"},
{word:"aftale", meaning:"anlaşma"},
{word:"aftensmad", meaning:"akşam yemeği"},
{word:"alder", meaning:"yaş"},
{word:"andel", meaning:"pay"},

{word:"ansøgning", meaning:"başvuru"},
{word:"ansigtstræk", meaning:"yüz hatları"},
{word:"antal", meaning:"sayı"},
{word:"anledning", meaning:"fırsat"},
{word:"anmeldelse", meaning:"yorum - inceleme"},
{word:"arbejdserfaring", meaning:"iş deneyimi"},
{word:"arbejdsmiljø", meaning:"çalışma ortamı"},
{word:"arbejdsopgave", meaning:"iş görevi"},
{word:"arbejdskraft", meaning:"iş gücü"},
{word:"argument", meaning:"argüman"},

{word:"baggrund", meaning:"arka plan"},
{word:"balance", meaning:"denge"},
{word:"bankkonto", meaning:"banka hesabı"},
{word:"behov", meaning:"ihtiyaç"},
{word:"begreb", meaning:"kavram"},
{word:"begyndelse", meaning:"başlangıç"},
{word:"bekymring", meaning:"endişe"},
{word:"beløb", meaning:"miktar"},
{word:"beskrivelse", meaning:"tanım"},
{word:"beslutning", meaning:"karar"},

{word:"besøg", meaning:"ziyaret"},
{word:"betaling", meaning:"ödeme"},
{word:"bevægelse", meaning:"hareket"},
{word:"bevis", meaning:"kanıt"},
{word:"bevidsthed", meaning:"bilinç"},
{word:"betingelse", meaning:"şart"},
{word:"betydning", meaning:"anlam"},
{word:"billede", meaning:"resim"},
{word:"biodag", meaning:"sinema günü"},
{word:"branche", meaning:"sektör"},

{word:"budget", meaning:"bütçe"},
{word:"byggeri", meaning:"inşaat"},
{word:"byliv", meaning:"şehir hayatı"},
{word:"byområde", meaning:"şehir bölgesi"},
{word:"bæredygtighed", meaning:"sürdürülebilirlik"},
{word:"deltagelse", meaning:"katılım"},
{word:"demokrati", meaning:"demokrasi"},
{word:"detalje", meaning:"detay"},
{word:"dialog", meaning:"diyalog"},
{word:"diskussion", meaning:"tartışma"},

{word:"dokument", meaning:"belge"},
{word:"drøm", meaning:"hayal"},
{word:"effekt", meaning:"etki"},
{word:"eksempel", meaning:"örnek"},
{word:"energi", meaning:"enerji"},
{word:"erfaring", meaning:"deneyim"},
{word:"erhverv", meaning:"meslek"},
{word:"erklæring", meaning:"beyan"},
{word:"evne", meaning:"yetenek"},
{word:"faktor", meaning:"faktör"},

{word:"familieliv", meaning:"aile hayatı"},
{word:"fællesskab", meaning:"topluluk"},
{word:"færdighed", meaning:"beceri"},
{word:"feedback", meaning:"geri bildirim"},
{word:"fejltagelse", meaning:"hata"},
{word:"ferieplan", meaning:"tatil planı"},
{word:"forskning", meaning:"araştırma"},
{word:"forskel", meaning:"fark"},
{word:"forståelse", meaning:"anlayış"},
{word:"fortid", meaning:"geçmiş"},

{word:"fremtid", meaning:"gelecek"},
{word:"funktion", meaning:"fonksiyon"},
{word:"færdsel", meaning:"trafik"},
{word:"fænomener", meaning:"olaylar"},
{word:"færdselssikkerhed", meaning:"trafik güvenliği"},
{word:"færdighedsniveau", meaning:"beceri seviyesi"},
{word:"fællesmål", meaning:"ortak hedef"},
{word:"fællesinteresse", meaning:"ortak ilgi"},
{word:"fællesområde", meaning:"ortak alan"},
{word:"fællesskabets styrke", meaning:"topluluk gücü"},

{word:"gruppe", meaning:"grup"},
{word:"grund", meaning:"neden"},
{word:"grundlag", meaning:"temel"},
{word:"grundregel", meaning:"temel kural"},
{word:"helbred", meaning:"sağlık"},
{word:"hensigt", meaning:"niyet"},
{word:"historie", meaning:"tarih"},
{word:"holdning", meaning:"görüş"},
{word:"identitet", meaning:"kimlik"},
{word:"idéudvikling", meaning:"fikir geliştirme"},

{word:"indflydelse", meaning:"etki"},
{word:"indhold", meaning:"içerik"},
{word:"indsats", meaning:"çaba"},
{word:"indsigt", meaning:"içgörü"},
{word:"indstilling", meaning:"tutum"},
{word:"information", meaning:"bilgi"},
{word:"interesse", meaning:"ilgi"},
{word:"internet", meaning:"internet"},
{word:"jobmulighed", meaning:"iş fırsatı"},
{word:"kendskab", meaning:"bilgi - aşinalık"},

{word:"kompetence", meaning:"yetkinlik"},
{word:"konflikt", meaning:"çatışma"},
{word:"konklusion", meaning:"sonuç"},
{word:"kontakt", meaning:"iletişim"},
{word:"kultur", meaning:"kültür"},
{word:"kvalitet", meaning:"kalite"},
{word:"læring", meaning:"öğrenme"},
{word:"ledelse", meaning:"yönetim"},
{word:"livsstil", meaning:"yaşam tarzı"},
{word:"løsning", meaning:"çözüm"},

{word:"mulighed", meaning:"imkan"},
{word:"mål", meaning:"hedef"},
{word:"miljø", meaning:"çevre"},
{word:"motiv", meaning:"motiv"},
{word:"netværk", meaning:"ağ"},
{word:"niveau", meaning:"seviye"},
{word:"norm", meaning:"norm"},
{word:"nyhed", meaning:"haber"},
{word:"oplevelse", meaning:"deneyim"},
{word:"opfattelse", meaning:"algı"},

{word:"opgave", meaning:"görev"},
{word:"opinion", meaning:"görüş"},
{word:"opmærksomhed", meaning:"dikkat"},
{word:"ordning", meaning:"düzen"},
{word:"organisation", meaning:"organizasyon"},
{word:"oversigt", meaning:"genel bakış"},
{word:"periode", meaning:"dönem"},
{word:"person", meaning:"kişi"},
{word:"plan", meaning:"plan"},
{word:"politik", meaning:"politika"},

{word:"problemstilling", meaning:"problem durumu"},
{word:"proces", meaning:"süreç"},
{word:"produktion", meaning:"üretim"},
{word:"projekt", meaning:"proje"},
{word:"psykologi", meaning:"psikoloji"},
{word:"resultat", meaning:"sonuç"},
{word:"rolle", meaning:"rol"},
{word:"samfund", meaning:"toplum"},
{word:"sammenhæng", meaning:"bağlantı"},
{word:"samarbejde", meaning:"işbirliği"},

{word:"situation", meaning:"durum"},
{word:"strategi", meaning:"strateji"},
{word:"struktur", meaning:"yapı"},
{word:"succes", meaning:"başarı"},
{word:"system", meaning:"sistem"},
{word:"teknologi", meaning:"teknoloji"},
{word:"tema", meaning:"tema"},
{word:"teori", meaning:"teori"},
{word:"tilgang", meaning:"yaklaşım"},
{word:"tilstand", meaning:"durum"},

{word:"udvikling", meaning:"gelişim"},
{word:"udfordring", meaning:"zorluk"},
{word:"uddannelse", meaning:"eğitim"},
{word:"værdi", meaning:"değer"},
{word:"virksomhed", meaning:"şirket"},
{word:"vækst", meaning:"büyüme"},
{word:"viden", meaning:"bilgi"},
{word:"vilkår", meaning:"şartlar"},
{word:"virkning", meaning:"etki"},
{word:"økonomi", meaning:"ekonomi"}

];