const title = "Ordsæt-3 💬";

const defaultWords = [

{word:"abstraktion", meaning:"soyutlama"},
{word:"accept", meaning:"kabul"},
{word:"adfærd", meaning:"davranış"},
{word:"adgang", meaning:"erişim"},
{word:"afhængighed", meaning:"bağımlılık"},
{word:"afledning", meaning:"çıkarım"},
{word:"afspejling", meaning:"yansıma"},
{word:"afvejning", meaning:"denge kurma"},
{word:"analyse", meaning:"analiz"},
{word:"anerkendelse", meaning:"tanıma"},

{word:"anskuelse", meaning:"bakış açısı"},
{word:"antagelse", meaning:"varsayım"},
{word:"argumentation", meaning:"argümantasyon"},
{word:"autoritet", meaning:"otorite"},
{word:"bagvedliggende årsag", meaning:"altta yatan neden"},
{word:"begrænsning", meaning:"sınırlama"},
{word:"begrundelse", meaning:"gerekçe"},
{word:"bekræftelse", meaning:"doğrulama"},
{word:"belastning", meaning:"yük - stres"},
{word:"berettigelse", meaning:"haklılık"},

{word:"beskaffenhed", meaning:"özellik"},
{word:"bestræbelse", meaning:"çaba"},
{word:"betegnelse", meaning:"tanımlama"},
{word:"betragtning", meaning:"değerlendirme"},
{word:"bevisførelse", meaning:"kanıtlama"},
{word:"betinget udvikling", meaning:"koşullu gelişim"},
{word:"bevidsthedsniveau", meaning:"bilinç seviyesi"},
{word:"dannelse", meaning:"kültürel oluşum"},
{word:"definition", meaning:"tanım"},
{word:"dimension", meaning:"boyut"},

{word:"diskurs", meaning:"söylem"},
{word:"dominans", meaning:"baskınlık"},
{word:"drøftelse", meaning:"tartışma"},
{word:"effektivitet", meaning:"verimlilik"},
{word:"egenskab", meaning:"özellik"},
{word:"erkendelse", meaning:"farkındalık"},
{word:"essens", meaning:"öz"},
{word:"etik", meaning:"etik"},
{word:"evaluering", meaning:"değerlendirme"},
{word:"eksistens", meaning:"varoluş"},

{word:"fænomen", meaning:"olgu"},
{word:"forandringsproces", meaning:"değişim süreci"},
{word:"forudsætning", meaning:"ön koşul"},
{word:"forventning", meaning:"beklenti"},
{word:"forvaltning", meaning:"yönetim"},
{word:"fremskridt", meaning:"ilerleme"},
{word:"funktionalitet", meaning:"işlevsellik"},
{word:"globalisering", meaning:"küreselleşme"},
{word:"grundprincip", meaning:"temel ilke"},
{word:"hensigtsmæssighed", meaning:"uygunluk"},

{word:"hierarki", meaning:"hiyerarşi"},
{word:"identifikation", meaning:"tanımlama"},
{word:"ideologi", meaning:"ideoloji"},
{word:"implementering", meaning:"uygulama"},
{word:"indikation", meaning:"gösterge"},
{word:"indvirkning", meaning:"etki"},
{word:"integritet", meaning:"bütünlük"},
{word:"interaktion", meaning:"etkileşim"},
{word:"intervention", meaning:"müdahale"},
{word:"konsekvens", meaning:"sonuç"},

{word:"kontekst", meaning:"bağlam"},
{word:"kontinuitet", meaning:"süreklilik"},
{word:"korrelation", meaning:"bağlantı"},
{word:"kriterium", meaning:"kriter"},
{word:"legitimitet", meaning:"meşruiyet"},
{word:"logik", meaning:"mantık"},
{word:"mekanisme", meaning:"mekanizma"},
{word:"metode", meaning:"yöntem"},
{word:"motivation", meaning:"motivasyon"},
{word:"nødvendighed", meaning:"zorunluluk"},

{word:"observation", meaning:"gözlem"},
{word:"omfang", meaning:"kapsam"},
{word:"opfattelse", meaning:"algı"},
{word:"optimering", meaning:"optimizasyon"},
{word:"paradigme", meaning:"paradigma"},
{word:"perspektiv", meaning:"bakış açısı"},
{word:"påvirkning", meaning:"etkileme"},
{word:"potentiale", meaning:"potansiyel"},
{word:"præmis", meaning:"öncül"},
{word:"problematik", meaning:"sorunsal"},

{word:"processtyring", meaning:"süreç yönetimi"},
{word:"produktionsevne", meaning:"üretim kapasitesi"},
{word:"relevans", meaning:"ilgili olma"},
{word:"ressource", meaning:"kaynak"},
{word:"resultatmåling", meaning:"sonuç ölçümü"},
{word:"retfærdighed", meaning:"adalet"},
{word:"risiko", meaning:"risk"},
{word:"sammenhængskraft", meaning:"bağlılık gücü"},
{word:"samspil", meaning:"etkileşim"},
{word:"selvstændighed", meaning:"bağımsızlık"},

{word:"signal", meaning:"sinyal"},
{word:"strukturering", meaning:"yapılandırma"},
{word:"subjektivitet", meaning:"öznellik"},
{word:"systematik", meaning:"sistematiklik"},
{word:"teoretisk grundlag", meaning:"teorik temel"},
{word:"tilpasning", meaning:"uyum"},
{word:"troværdighed", meaning:"güvenilirlik"},
{word:"udfordringsniveau", meaning:"zorluk seviyesi"},
{word:"udgangspunkt", meaning:"başlangıç noktası"},
{word:"udviklingspotentiale", meaning:"gelişim potansiyeli"},

{word:"uhensigtsmæssighed", meaning:"uygunsuzluk"},
{word:"usikkerhed", meaning:"belirsizlik"},
{word:"validitet", meaning:"geçerlilik"},
{word:"variation", meaning:"çeşitlilik"},
{word:"vurdering", meaning:"değerlendirme"},
{word:"værdisæt", meaning:"değerler bütünü"},
{word:"videnskab", meaning:"bilim"},
{word:"virkelighedsopfattelse", meaning:"gerçeklik algısı"},
{word:"vurderingskriterier", meaning:"değerlendirme kriterleri"},
{word:"årsagssammenhæng", meaning:"neden-sonuç ilişkisi"}

];