const title = "Ordsæt-1 💬";

const defaultWords = [
{word:"år", meaning:"yıl"},
{word:"dag", meaning:"gün"},
{word:"tid", meaning:"zaman"},
{word:"uge", meaning:"hafta"},
{word:"måned", meaning:"ay"},
{word:"morgen", meaning:"sabah"},
{word:"aften", meaning:"akşam"},
{word:"nat", meaning:"gece"},
{word:"minut", meaning:"dakika"},
{word:"sekund", meaning:"saniye"},

{word:"mand", meaning:"erkek"},
{word:"kvinde", meaning:"kadın"},
{word:"barn", meaning:"çocuk"},
{word:"familie", meaning:"aile"},
{word:"mor", meaning:"anne"},
{word:"far", meaning:"baba"},
{word:"søster", meaning:"kız kardeş"},
{word:"bror", meaning:"erkek kardeş"},
{word:"menneske", meaning:"insan"},
{word:"ven", meaning:"arkadaş"},

{word:"hus", meaning:"ev"},
{word:"lejlighed", meaning:"daire"},
{word:"værelse", meaning:"oda"},
{word:"køkken", meaning:"mutfak"},
{word:"bad", meaning:"banyo"},
{word:"bord", meaning:"masa"},
{word:"stol", meaning:"sandalye"},
{word:"seng", meaning:"yatak"},
{word:"dør", meaning:"kapı"},
{word:"vindue", meaning:"pencere"},

{word:"by", meaning:"şehir"},
{word:"land", meaning:"ülke"},
{word:"vej", meaning:"yol"},
{word:"plads", meaning:"yer"},
{word:"område", meaning:"alan"},
{word:"butik", meaning:"mağaza"},
{word:"skole", meaning:"okul"},
{word:"arbejde", meaning:"iş"},
{word:"firma", meaning:"şirket"},
{word:"kontor", meaning:"ofis"},

{word:"mad", meaning:"yemek"},
{word:"vand", meaning:"su"},
{word:"brød", meaning:"ekmek"},
{word:"kød", meaning:"et"},
{word:"fisk", meaning:"balık"},
{word:"mælk", meaning:"süt"},
{word:"ost", meaning:"peynir"},
{word:"frugt", meaning:"meyve"},
{word:"grøntsager", meaning:"sebze"},
{word:"kaffe", meaning:"kahve"},

{word:"bil", meaning:"araba"},
{word:"bus", meaning:"otobüs"},
{word:"tog", meaning:"tren"},
{word:"cykel", meaning:"bisiklet"},
{word:"metro", meaning:"metro"},
{word:"rejse", meaning:"seyahat"},
{word:"station", meaning:"istasyon"},
{word:"billet", meaning:"bilet"},
{word:"trafik", meaning:"trafik"},
{word:"vej", meaning:"yol"},

{word:"penge", meaning:"para"},
{word:"pris", meaning:"fiyat"},
{word:"løn", meaning:"maaş"},
{word:"konto", meaning:"hesap"},
{word:"bank", meaning:"banka"},
{word:"betaling", meaning:"ödeme"},
{word:"regning", meaning:"fatura"},
{word:"køb", meaning:"alışveriş"},
{word:"salg", meaning:"satış"},
{word:"tilbud", meaning:"teklif"},

{word:"problem", meaning:"problem"},
{word:"løsning", meaning:"çözüm"},
{word:"idé", meaning:"fikir"},
{word:"spørgsmål", meaning:"soru"},
{word:"svar", meaning:"cevap"},
{word:"information", meaning:"bilgi"},
{word:"besked", meaning:"mesaj"},
{word:"historie", meaning:"hikaye"},
{word:"nyhed", meaning:"haber"},
{word:"plan", meaning:"plan"},

{word:"krop", meaning:"vücut"},
{word:"hoved", meaning:"baş"},
{word:"hånd", meaning:"el"},
{word:"fod", meaning:"ayak"},
{word:"øje", meaning:"göz"},
{word:"øre", meaning:"kulak"},
{word:"mund", meaning:"ağız"},
{word:"næse", meaning:"burun"},
{word:"arm", meaning:"kol"},
{word:"ben", meaning:"bacak"},

{word:"tøj", meaning:"kıyafet"},
{word:"sko", meaning:"ayakkabı"},
{word:"jakke", meaning:"ceket"},
{word:"bukser", meaning:"pantolon"},
{word:"shirt", meaning:"tişört"},
{word:"hat", meaning:"şapka"},
{word:"taske", meaning:"çanta"},
{word:"lomme", meaning:"cep"},
{word:"ur", meaning:"saat"},
{word:"briller", meaning:"gözlük"},

{word:"vejr", meaning:"hava"},
{word:"sol", meaning:"güneş"},
{word:"regn", meaning:"yağmur"},
{word:"sne", meaning:"kar"},
{word:"vind", meaning:"rüzgar"},
{word:"sky", meaning:"bulut"},
{word:"temperatur", meaning:"sıcaklık"},
{word:"sommer", meaning:"yaz"},
{word:"vinter", meaning:"kış"},
{word:"forår", meaning:"ilkbahar"}
];